// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bedwguwfqcqrzwdhgflb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlZHdndXdmcWNxcnp3ZGhnZmxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MDE4MzIsImV4cCI6MjA4NjQ3NzgzMn0.PHx6JH4LZhllAnCrqTxl9uUHfvYW8ocF4j7qD1d7VHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);