// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://squzevnsyszajkkfzgub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxdXpldm5zeXN6YWpra2Z6Z3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTkwMjgsImV4cCI6MjA2Mzc3NTAyOH0.cYG9ymQuOj_hxiiPKEKfUQ4P5U_dSC5NpVxYk5Ge8Fc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);